### ISSUE TITLE
Error when making phase 'in progress'

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2416]
Sometimes when I switch phase to `in progress` status, I get error in browsers console:
```
productsTimelines.js:133 Uncaught (in promise) TypeError: Cannot read property '-1' of undefined
    at eval (productsTimelines.js:133)
    at eval (index.js:11)
    at eval (index.js:49)
    at dispatch (applyMiddleware.js:37)
    at optionallyUpdateFirstMilestone (project.js:417)
```

Error in the next line:

![image](https://user-images.githubusercontent.com/146016/44459016-a6b51780-a63a-11e8-8358-d924ed2871f0.png)

The error happens during attempt to mark the first milestone as `active`. After that we end up when phase is already `in progress` but there is no active milestone.

![image](https://user-images.githubusercontent.com/146016/44459093-ebd94980-a63a-11e8-9595-746edb5dbabb.png)

This error happens occasionlly.

**Comment by maxceem** [comment]
This happened every time when we create a new Visual Design project and mark the only phase default phase as `in progress`.

Fixed via https://github.com/appirio-tech/connect-app/commit/e51ef016fdfb29769b9c8d394e8bcd3ec92b8726

**Comment by vikasrohit** [comment]
Good observation @maxceem. I can understand that update timeline call does not return milestones in response, which seems to the issue here, however I am still wondering why it was not happening for other type of projects/phases.

**Comment by maxceem** [comment]
@vikasrohit The reason is that after updating phase we update timeline only in case when phase start date is changed or phase is activated https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/project.js#L421

**Comment by vikasrohit** [comment]
Yup, Agreed, but it still does not answer that why it was happening only for a specific type of project or phase.

**Comment by maxceem** [comment]
I didn't check for other project types, but I believe it has to happen for
all types. I've mentioned the type of project in the issue just to be sure
that the issue can be reproduced with my instructions.

**Comment by vikasrohit** [comment]
👍

**Comment by vikasrohit** [comment]
Working fine. Closing.
