### ISSUE TITLE
[$30] Enabling changing of user mail via Connect-app only by customers

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2710]
Right now the email can't be changed from the `Account` page of connect as earlier we didn't had support of redirect URL to Connect(or any other custom URL). but with this change (https://github.com/appirio-tech/ap-member-microservice/pull/198 )in place in member service we are good to go for enabling users to change the email from connect as well.

fyi @acshields @vikasrohit

**Comment by maxceem** [comment]
@RishiRajSahu 

I see that relative change is implemented in Member Service https://github.com/appirio-tech/ap-member-microservice/pull/198/files and merged to DEV.

I've checked worklow which is implemented and it's like this:
- When we update member profile's email we have to define `successUrl` and `failUrl`, which is good, so we call update endpoint like this:
    ```
    POST https://api.topcoder-dev.com/v3/members/maxceem/?successUrl=connect.topcoder-dev.com%2Fsettings%2Faccount%2Femail-verification%2Fsuccess&failUrl=connect.topcoder-dev.com%2Fsettings%2Faccount%2Femail-verification%2Ffailure
    ```
    And in the body we are sending member profile with updated email. This part is clear.
- After that backend sends verification email with a link to click which looks like this:
    ```
    https://community-app.topcoder-dev.com/v3/members/maxceem/verify?action=verify&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJhc2RkIiwiY29waWxvdCJdLCJpc3MiOiJodHRwczovL2FwaS50b3Bjb2Rlci1kZXYuY29tIiwiaGFuZGxlIjoibWF4Y2VlbSIsImV4cCI6MTU0NjQ5ODQ4NCwidXNlcklkIjoiNDAwMzUyOTEiLCJpYXQiOjE1NDY0OTc4ODQsImVtYWlsIjoibWF4Y2VlbUBnbWFpbC5jb20iLCJqdGkiOiI4YjQ1MGJmZC05ZTI5LTQwY2ItOWFmYy1iYmQxMDM0YzMwYjQifQ.ar027LU8FnOYIQIW9pCZtzzY2mAuRLI6XeIEjqSulrk&newEmail=maks.m@inbox.ru&oldEmail=maxceem@gmail.com&redirectTo={successUrl}
    ```

So there are two things:
1. The workflow depends on the community app frontend. As backend sends link which goes to Community App anyway, not to `successUrl`. And as I see in member service code it's hardcoded. I mean it will be always the link to community app. Looks like the idea is that we will go to commynity app anyway, and community app has to verify email and after community app has to redirect to `successUrl` which we can define to be the URL in Connect App.
2.There is issue in backend as `successUrl` in the link is not replaced with `successUrl` which I've passed to the update email endpoint.

I'm not sure why such appraoch has been chosen in implementing `successUrl`/`failUrl` as we still have to show to our customers Community App instead of directly redirecting them to Connect App. And we are depending on the Commynity App as it has to redirect user to Connect App. So Community App has to implement this feature and has to also work properly and be alive when customers of Connect App change email.

What do you think?

**Comment by maxceem** [comment]
@RishiRajSahu if you wanna try it yourself here is the branch where I've enabled email changing and added support for `successUrl` and `failUrl` https://github.com/appirio-tech/connect-app/tree/feature/account-settings-improvements

**Comment by RishiRajSahu** [comment]
@maxceem yeah its visible that the baseURL should be replaced with the domain of MemberService only, Let me check the respective changes in community app for this update in member service.

**Comment by RishiRajSahu** [comment]
fyi @maxceem  https://github.com/topcoder-platform/community-app/commit/1bfb71e21a8bfc912f7e4a916955923238726e65

**Comment by maxceem** [comment]
@RishiRajSahu Thanks for the link to update in community App. I've checked the implementation inside Community App.

#### Commynity App

The implementation doesn't work as it includes `successUrl` and `failUrl` inside profile data instead of adding these params to the URL:

![image](https://user-images.githubusercontent.com/146016/50670095-2351fc80-1004-11e9-9213-f170a849229b.png)

So this request to update email is rejected by server by two reasons:
- profile data cannot contain `successUrl` and `failUrl`
- URL **has** to cotain `successUrl` and `failUrl` when we are changing email

But, even if this is fixed, changing email still won't work. As the code which verifies email was removed in Community App, but it's still needed. And also route in Commynity App has been changed https://github.com/topcoder-platform/community-app/commit/1bfb71e21a8bfc912f7e4a916955923238726e65#diff-bb1f789bc22dd44ec81af6b39fc06951L19 but backend doesn't send link to this route.

#### Member Service

IMHO, the best way to go is ask member service team to slightly change member service so they send email with `successUrl` and `failUrl` which we provide instead of predefined:
```
verificationAgreeUrl: "{baseUrl}/v3/members/{handle}/verify?action=verify&token={jwtToken}&newEmail={newEmail}&oldEmail={oldEmail}&redirectTo={successUrl}"
  verificationDisagreeUrl: "{baseUrl}/v3/members/{handle}/verify?action=cancel&token={jwtToken}&newEmail={newEmail}&oldEmail={oldEmail}&redirectTo={failUrl}"
```
Note, that currently backend send link like this:
![image](https://user-images.githubusercontent.com/146016/50670494-ef2c0b00-1006-11e9-9cc0-315587af5194.png)

This link leads to `/v3/members/maxceem/verify` which is endpoint of backend API, not link in Commynity App. 

If backend can send email with a link we provide after that, inside Community App they can revert the current fix, and instead they only need to provide `successUrl` and `failUrl` in the request and the rest of logic will stay for them.

In Connect App everything is also ready same like in Commynity App, so we will only need to provide `successUrl` and `failUrl` in the request.

What do you think?

**Comment by maxceem** [comment]
This feature is enabled in https://github.com/appirio-tech/connect-app/tree/feature/account-settings-improvements branch now.

Though looks like there is an issue with member service.
- when I ask to change email
- I get a email with a link to confirm, which looks good:

  ![image](https://user-images.githubusercontent.com/146016/51293196-b4839300-1a48-11e9-8515-7d26df128461.png)

- when I open it in the brwoser I got error:

  ```
   {"id":"-20fea014:168579b92c1:-58ec","result":{"success":true,"status":401,"metadata":null,"content":"Valid credentials are required to access this resource."},"version":"v3"}
  ```

- the token looks also good:
   
   ![image](https://user-images.githubusercontent.com/146016/51293263-13e1a300-1a49-11e9-9fe8-6c3cd84bb505.png)

**Comment by RishiRajSahu** [comment]
@maxceem created issue https://github.com/appirio-tech/ap-member-microservice/issues/213 to get this working.

**Comment by RishiRajSahu** [comment]
fyi @maxceem updated the title as we need this option to be enabled for customers only.

**Comment by RishiRajSahu** [comment]
fyi @maxceem the member service changes is in dev for this https://github.com/appirio-tech/ap-member-microservice/pull/215

**Comment by maxceem** [comment]
Sum up:
- Currently, we enabled the ability to change email for all users, see https://connect.topcoder-dev.com/settings/account
   
   ![image](https://user-images.githubusercontent.com/146016/55325186-d96b9c00-54b6-11e9-83f6-3887cd44a8a2.png)

- Instead, only customer users should be able to change their email here. For the rest of users email field should be disabled.

@RishiRajSahu do I understand it correctly, that we a customer user is any user which doesn't have any of these roles https://github.com/appirio-tech/connect-app/blob/dev/src/config/constants.js#L567-L572. So customer can only have `Topcoder User` role.

**Comment by RishiRajSahu** [comment]
@maxceem yep customers are defined as ones who only have single role - `Topcoder User`

**Comment by Gauravseta** [comment]
@maxceem please assign this to me thanks

**Comment by maxceem** [comment]
done

**Comment by Gauravseta** [comment]
@maxceem it is ready https://github.com/appirio-tech/connect-app/pull/2946.

but i guess pshah_customer is no more a customer. because it gives other roles too in its user object. so i guess a new customer account is required

**Comment by Gauravseta** [comment]
@maxceem MR is update now. It was my fault of not passing props to respective component.

**Comment by RishiRajSahu** [comment]
@maxceem disabling it for time being https://github.com/appirio-tech/connect-app/commit/d6fea9c3bdfd4d41f4cc4ec4e1e4029ba7aa4985, will take this in next release.

**Comment by vikasrohit** [comment]
Moving to next release again as we still don't have green signal to release this feature.

**Comment by RishiRajSahu** [comment]
Done and pushed to prod.
