### ISSUE TITLE
[$20] IE 11 minor visual issues

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3435]
I've noticed some minor visual issues in IE 11:

![image](https://user-images.githubusercontent.com/146016/70877763-bc9dd700-1ff9-11ea-8c43-ef9a7ed60f2b.png)

1. Should we fix them?

2. Do we have the list of browsers we intend to support?<br>
    I guess it would be best if we define the list of browsers to support based on the actual browser statistics of **Connect App** users. As far as I know, we use Google Analytics, so we can get our actual browser statistics from there and create a list of browsers to support.
     Meanwhile I found several general statistics, but their results are varied quite heavily:
    - https://netmarketshare.com/browser-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browser%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktop%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222018-12%22%2C%22dateEnd%22%3A%222019-11%22%2C%22segments%22%3A%22-1000%22%7D
    - https://gs.statcounter.com/
    - https://www.stetic.com/market-share/browser/

**Comment by vikasrohit** [comment]
@maxceem I think we support IE11, but I would confirm again.

**Comment by vikasrohit** [comment]
@maxceem please try to include this one in next bug bash.

**Comment by Gauravseta** [comment]
@bug-bash-helper assign

**Comment by Gauravseta** [comment]
@bug-bash-helper unassign

**Comment by rashmi73** [comment]
@bug-bash-helper assign

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3763 is ready for review

**Comment by satkanhub** [comment]
Notification count next to Dashboard is not aligned. I could see the issue in IE11 and Chrome. 

IE11
![image](https://user-images.githubusercontent.com/51492004/76691337-2ace5600-664a-11ea-8cb9-d85b308dd98f.png)

Chrome
![image](https://user-images.githubusercontent.com/51492004/76691363-708b1e80-664a-11ea-921b-71897d1670fb.png)

**Comment by maxceem** [comment]
@satkanhub this is indeed a regression issue.

**Comment by maxceem** [comment]
regression issue is fixed

**Comment by drasticdpk** [comment]
@maxceem  above issue has been verified on IE browser.
![image](https://user-images.githubusercontent.com/25297859/76728895-fd83c400-677f-11ea-9efc-c86bada90733.png)

But we can see there are other discrepancy between IE and Chrome browser in application. 
If the browser compatibility testing is in our scope, we can create separate issue for that. (if yes please mention the browser name which we have to test) cc @lakshmiathreya 
Here is the reference :
![image](https://user-images.githubusercontent.com/25297859/76729515-6fa8d880-6781-11ea-9b7f-519e79333e64.png)

**Comment by maxceem** [comment]
@drasticdpk in this issue we only fixed 2 cases mentioned in the issue description. It didn't include fixing any possible inconsistencies in IE11

For any new issues in IE11, please feel free to create new issues.

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects?sort=lastActivityAt%20desc
CustomerUser/appirio123

The view is not matched with the chrome browser. this is not fixed on production

![image](https://user-images.githubusercontent.com/62358241/78243947-55515780-7502-11ea-9fa3-320302919bae.png)

**Comment by maxceem** [comment]
@coderhacker in this issue we only fixed 2 issues illustrated in the description https://github.com/appirio-tech/connect-app/issues/3435#issue-538170495. Let's track other issues in a new issue.

**Comment by vikasrohit** [comment]
@coderhacker Please add your final QA comments here. I am marking it as passed for now as the reason of failure seems to be a new finding.
