### ISSUE TITLE
Choose country code for phone using dropdown is broken

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3823]
### Expected behavior
We should be able to change the country and code by the dropdown next to the phone field.

### Actual behavior
When we click any country in the dropdown code and country is not changed.

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/146016/78112904-9153c200-7407-11ea-8d05-2346e9f60444.png)

- Open user profile settings page https://connect.topcoder-dev.com/settings/profile
- Click the country code dropdown next to the **Business Phone** phone field and choose any country.
- Observe that it didn't make any effect and country and code is not changed.

### Screenshot/screencast

![switch-country](https://user-images.githubusercontent.com/146016/78113004-be07d980-7407-11ea-96d1-95eb549737db.gif)

### Related issues

https://github.com/appirio-tech/connect-app/issues/3823
https://github.com/appirio-tech/connect-app/issues/3822

**Comment by maxceem** [comment]
The interesting thing, that this functionality works on the registration form page https://accounts.topcoder-dev.com/connect/registration. So the preferred way to fix it if possible is to move this logic to the [PhoneIntput](https://github.com/appirio-tech/react-components/blob/7795f6f1758dab4cf2cded76a62504fa619bf1d0/components/Formsy/PhoneInput.jsx) component, so it would work automatically in all the places instead of implementing duplicate logic in Connect App.

**Comment by maxceem** [comment]
This has been fixed via https://github.com/appirio-tech/connect-app/pull/3824 and https://github.com/appirio-tech/react-components/pull/357.

We had to make sure that `react-components` uses `libphonenumber-js` version `1.4.6`  instead of the newer version `1.7.48` by updating rule in `package.json` from `^1.4.6` to `1.4.6`.

**Comment by lakshmiathreya** [comment]
The drop down for Country code for phone seems to be working on Dev now - however, the scroll bar is not visible - so picking Country in Business Phone continues to work only via the Country field even now ... pls clarify if this is a must do for 2.8 release ...

**Comment by lakshmiathreya** [comment]
@codejamtc @coderhacker

**Comment by codejamtc** [comment]
@maxceem @lakshmiathreya I am validating this one now, still not finished yet. I have seen a bunch of issues.

Ref: https://countrycode.org/

**NOTE: Two scrollbars displayed**

![image](https://user-images.githubusercontent.com/42398485/78156567-95caab80-7404-11ea-8ded-66689972a217.png)


1. When you select `Aland Islands` the code is displayed as `FIN` 
https://laendercode.net/en/2-letter-code/ax

2.  When you select `American Samoa` the code is displayed as `US` , should be `ASM`

3. When you select `Anguilla` the code is displayed as `US` , should be `AIA`

4. Can't select `Antarctica`

5. When you select `Antigua and Barbuda` the code is displayed as `US` , should be `ATG`

**Comment by maxceem** [comment]
@lakshmiathreya could you please specify the issue with scrollbar, as I can see and use the scrollbar:

![country-scroll](https://user-images.githubusercontent.com/146016/78156579-a6504580-7447-11ea-886f-e058db2c9c42.gif)

**Comment by codejamtc** [comment]
Ref: https://countrycode.org/

- Can't select `Antarctica`
- Can't select `Bouvet Island`
- Can't select `Heard Island and McDonald Islands`
- Can't select `Pitcairn`
- Can't select `South Georgia and the South Sandwich island`


@vikasrohit @maxceem @lakshmiathreya There are few issues in the list, like Selecting some countries will select `US` from the list NOT the original country, Some country codes are incorrect, Some numbers are incorrect. I think we need to refine the list completely.

**Comment by maxceem** [comment]
@codejamtc current issue was about fixing selecting countries in general, as it was completely broken and we couldn't select any countries.

I suggest marking this issue are pass and I've created separate issues to cover the bug you've found:
- double scrollbar https://github.com/appirio-tech/connect-app/issues/3832
- cannot choose some particular countries and wrong codes https://github.com/appirio-tech/connect-app/issues/3831

**Comment by codejamtc** [comment]
@maxceem As all the issues are moved into another ticket, I will mart this one as `Pass`

**Comment by codejamtc** [comment]
Verified in `Prod`: 🆗 Pass. Only checked the dropdown item selection, there are still issues related this this area (in Dev also) https://github.com/appirio-tech/connect-app/issues/3831, https://github.com/appirio-tech/connect-app/issues/3832, https://github.com/appirio-tech/connect-app/issues/3823#issuecomment-607344925
**User:** CustomerUser

https://monosnap.com/file/5Loqeh8xsgWQ4GWxnaiI6npQlH1rZK
