### ISSUE TITLE
Update copy for new connect register flow in logged out project creation flow

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#960]
@fnisen As we discussed some time ago over call, we need to update the copy(`Your project was saved successfully`) shown on the top of the registration and pin verification pages while following the logged out project creation flow.
<img width="707" alt="screen shot 2017-07-10 at 11 40 52 am" src="https://user-images.githubusercontent.com/2417632/28004820-abbd0872-6564-11e7-9a6d-b5c1c7f92610.png">
I have put a logic to dynamically show this message based on context i.e. we can show different header/title when user is registering in project flow and registering without project flow. Right now that logic is done only for pin verification page though.

**Comment by fnisen** [comment]
@vikasrohit I reviewed copy for the entire project creation/reg flow (except for some details on the spec pages) and summarized all edits and updates here: https://docs.google.com/a/appirio.com/document/d/1tGdqKq8uKyRiz06v6vXdwsMi5tOmWrvYL4MxtXKnU44/edit?usp=sharing. Can you please review and make the changes? Let me know if you have questions.

**Comment by fnisen** [comment]
@vikasrohit what's the status for this one please?

**Comment by vikasrohit** [comment]
Changes were done with #953 but waiting for bug hunt to wrap up. I merged it today, so dev should have all these changes and few others from community.
PS: We are still using "Your project has been saved. Now please create an account or login to submit it for review." for registration page title.

**Comment by fnisen** [comment]
@vikasrohit, yeah that was not looking good: 

![screen shot 2017-08-01 at 9 33 08 am](https://user-images.githubusercontent.com/12552247/28854593-eaf47b1c-76ec-11e7-8b6f-db1afb3841cf.png)

![screen shot 2017-08-01 at 9 34 35 am](https://user-images.githubusercontent.com/12552247/28854598-f9e0340e-76ec-11e7-928c-e3c2d1c323cb.png)


Also, headline here is the wrong size:

![screen shot 2017-08-01 at 4 25 48 pm](https://user-images.githubusercontent.com/12552247/28854599-005d445c-76ed-11e7-8ea2-1e51f0e9a63e.png)

**Comment by vikasrohit** [comment]
@fnisen I think instead the login page's heading is having wrong size as per new styles. In this new design we are using h3 for form heading and h2 for page heading. All pages are following that, except login page where form heading is h2 and that is the reason it is looking bigger. Please let me know how we want to fix it. @vic-topcoder

**Comment by vikasrohit** [comment]
@fnisen What we want to put as page headings now as two liners are not looking good?

**Comment by vic-topcoder** [comment]
We are mistaking page heading for status message...which would cause such a design disaster :D.

If we're building an intricate user-friendly messages, let's not use the title for them.

Right now the title is asking for a thing to do on the page, and the explanation of what happened is somewhere underneath.

![screen shot](https://user-images.githubusercontent.com/8484061/28889889-4b5e2650-777a-11e7-8017-a8ddcef74289.png)

**Comment by fnisen** [comment]
@vic-topcoder let's discuss tomorrow in detail. The issue is that we can't easily modify the form each time to convey a new message (@vikasrohit correct me if I'm wrong). We're relying on the page heading to be a flexible message. Vikas, let me know if you have any other ideas.

**Comment by vikasrohit** [comment]
> The issue is that we can't easily modify the form each time to convey a new message

@fnisen May be I have not understood properly, however, if you are concerned about showing status messages like we are showing on reset password form, in green color, I think it is not quite difficult here to achieve. If we have events to show statuses, we can show status messages.

**Comment by fnisen** [comment]
@vikasrohit discussed this with Vic. We need to change the flow to convey progress and have clearer messaging and we'll design this later. For now, can you please put those two-line page titles into a notification toaster instead?

**Comment by vikasrohit** [comment]
@fnisen @vic-topcoder Toaster is not integrated yet with accounts app. So, we have to show the messages as green boxes which we are showing on reset password page, after successful reset of password, to show the status of the flow.

**Comment by fnisen** [comment]
@vikasrohit would you want to put the green box at the top, where the current headlines are? Is that even possible? Let's do that if it's easy. Please do it in Dev first and let's check it out. 

If not, how long would it take to implement the toaster? Just wondering if we should do that as a stopgap or just work on the new design.

**Comment by vikasrohit** [comment]
@fnisen @vic-topcoder Please find screenshots below with green boxes at the top for showing the messages instead of using page headlines.

<img width="1023" alt="screen shot 2017-08-15 at 3 55 48 pm" src="https://user-images.githubusercontent.com/2417632/29312333-7813c21a-81d2-11e7-80f3-ac377f1683f9.png">
<img width="1035" alt="screen shot 2017-08-15 at 3 56 47 pm" src="https://user-images.githubusercontent.com/2417632/29312339-7daed0b6-81d2-11e7-8d61-f8b5c794ce4f.png">

**Comment by fnisen** [comment]
@vikasrohit this is looking good to me! Vic is out for a few days, so let's go with this and tweak later if needed. One note: "log in" is two words when it's used as a verb (on the first screenshot).

**Comment by vikasrohit** [comment]
Okay. Done. I have merged changes into dev branch, but haven't deployed yet to production. Please let me know if we need to deploy it. I think this is the only change we have right now for production.

**Comment by vic-topcoder** [comment]
Let's style it a little bit - it is too ugly right now.

![screen shot 2](https://user-images.githubusercontent.com/8484061/29644857-95f2a712-882e-11e7-9767-c9ca3a0b5047.png)
![screen shot](https://user-images.githubusercontent.com/8484061/29644858-99e1dadc-882e-11e7-961e-c5fedd06929f.png)

**Comment by vikasrohit** [comment]
Okay. Done.

**Comment by fnisen** [comment]
@vikasrohit not seeing it in Dev. Still get the full bar, like so: 

![screen shot 2017-08-24 at 12 25 08 pm](https://user-images.githubusercontent.com/12552247/29684565-4dd4de7a-88c7-11e7-88b0-bd914f224e77.png)

**Comment by vikasrohit** [comment]
Oh, I guess I forget to merge the branch. It would be in dev today.

**Comment by fnisen** [comment]
Working now, thanks.
